apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-application
  namespace: argocd
spec:
  destination:
    namespace: kafka-cluster-ns  # Target namespace for deployment
    server: https://kubernetes.default.svc
  source:
    path: helm # Path to your application manifests
    repoURL: https://github.com/findnanda/confluent-kafka-cluster-provisioner.git  # Git repository URL
    targetRevision: HEAD  # Branch, tag, or commit to deploy
    helm:
      valueFiles:
        - helm/values.yaml  # Helm values file if using Helm charts
  project: default  # Argo CD project
  syncPolicy:
    automated:
      prune: true  # Automatically prune resources
      selfHeal: true  # Automatically sync when changes detected
    syncOptions:
      - CreateNamespace=true  # Create namespace if it doesn't exist
