apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
spec:
  replicas: {{ .Values.replicaCount.schemaRegistry }}
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: {{ .Values.image.schemaRegistry }}
          ports:
            - containerPort: {{ .Values.service.schemaRegistry.port }}
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka:9092"
