apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: {{ .Values.service.zookeeper.type }}
  ports:
    - port: {{ .Values.service.zookeeper.port }}
      targetPort: {{ .Values.service.zookeeper.port }}
  selector:
    app: zookeeper
